stages:
    - build
    - deploy
    - checking
build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - mvn install -DskipTest=true
    tags:
        - devopslab

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - java -jar /target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar
    tags:
        - devopslab
